// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG9bnJgQ7CliMvU5nPUBAKwnvLpfb5AaM',
    appId: '1:1024278897620:web:c1abcbd7664d20ef40ec41',
    messagingSenderId: '1024278897620',
    projectId: 'movie-booking-app-917b3',
    authDomain: 'movie-booking-app-917b3.firebaseapp.com',
    storageBucket: 'movie-booking-app-917b3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJGrTy3zbMNcuUZbZz5FEuijn88gOv4tI',
    appId: '1:1024278897620:android:75f0be593ce0672840ec41',
    messagingSenderId: '1024278897620',
    projectId: 'movie-booking-app-917b3',
    storageBucket: 'movie-booking-app-917b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDNPoygWfclKq6T-6ZHTWt0zgQ6iCv1j8',
    appId: '1:1024278897620:ios:aa0e987f6287f55b40ec41',
    messagingSenderId: '1024278897620',
    projectId: 'movie-booking-app-917b3',
    storageBucket: 'movie-booking-app-917b3.firebasestorage.app',
    iosBundleId: 'com.example.movieBooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG9bnJgQ7CliMvU5nPUBAKwnvLpfb5AaM',
    appId: '1:1024278897620:web:8a57c55614ff3c0940ec41',
    messagingSenderId: '1024278897620',
    projectId: 'movie-booking-app-917b3',
    authDomain: 'movie-booking-app-917b3.firebaseapp.com',
    storageBucket: 'movie-booking-app-917b3.firebasestorage.app',
  );

}